server : 
  port : 8110

api:
  yahoo-finance:
    domain: 'query1.finance.yahoo.com/v7/finance/quote?symbols='
    endpoint: '0005.HK,0011.HK,0066.HK,0388.HK,0700.HK,0823.HK,0941.HK,1810.HK,3690.HK,9988.HK'
    crumb: '&crumb='
    # header

  yahoo-finance-history:
    domain: 'query1.finance.yahoo.com'
    history:
      base-path: 'v8/finance/chart'
      endpoint: '/0005.HK,/0011.HK,/0066.HK,/0388.HK,/0700.HK,/0823.HK,/0941.HK,/1810.HK,/3690.HK,/9988.HK'

database:
  db-name: "yahoodata" 

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update