server :
  port : 8104

api:
  yahoo-finance:
    domain: 'query1.finance.yahoo.com'
    history:
      base-path: 'v8/finance/chart'
      endpoint: '/0388.HK,/0005.HK,/0700.HK'
     #  hke: '/0388.HK'
     #  hsbc: '/0005.HK'
     #  tcl: '/0700.HK'

database:
  db-name: "bc-stock-web"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)